# dependabot.yml file with updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'tuesday'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'direct'
